/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface GwCommentsBody {
  /**
   * 创建人
   */
  "adder": number;
  /**
   * 创建时间
   */
  "addtime": string;
  /**
   * 评价时间
   */
  "comment_createtime": string;
  /**
   * 评价图片
   */
  "comment_images": string;
  /**
   * 评价内容
   */
  "comment_info": string;
  /**
   * 评价星级
   */
  "comment_star": number;
  /**
   * 修改人
   */
  "moder": number;
  /**
   * 修改时间
   */
  "modtime": string;
  /**
   * 订单号
   */
  "order_code": string;
  /**
   * 用户id
   */
  "order_commentor": number;
}

