/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface GwOrdersIdBody {
  /**
   * 创建人
   */
  "adder": number;
  /**
   * 创建时间
   */
  "addtime": string;
  /**
   * 修改人
   */
  "moder": number;
  /**
   * 修改时间
   */
  "modtime": string;
  /**
   * 用户id
   */
  "order_buyer": number;
  /**
   * 订单号
   */
  "order_code": string;
  /**
   * 是否失效
   */
  "order_isinvalid": number;
  /**
   * 是否退款
   */
  "order_isrefund": number;
  /**
   * 是否使用
   */
  "order_isused": number;
  /**
   * 购买总价（元）
   */
  "order_payprice": number;
  /**
   * 购买日期
   */
  "order_paytime": string;
  /**
   * 支付方式
   */
  "order_paytype": number;
  /**
   * 退款金额
   */
  "order_refundprice": number;
  /**
   * 退款日期
   */
  "order_refundtime": string;
  /**
   * 订单备注
   */
  "order_remark": string;
  /**
   * 订单总价（元）
   */
  "order_totalprice": number;
  /**
   * 订单ID
   */
  "orderid": number;
  /**
   * 套餐号
   */
  "pkg_code": string;
}

