/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface GwPackagedetailsBody {
  /**
   * 创建人
   */
  "adder": number;
  /**
   * 创建时间
   */
  "addtime": string;
  /**
   * 修改人
   */
  "moder": number;
  /**
   * 修改时间
   */
  "modtime": string;
  /**
   * 套餐号
   */
  "pkg_code": string;
  /**
   * 商品名称
   */
  "pkgdetail_name": string;
  /**
   * 数量
   */
  "pkgdetail_nums": number;
  /**
   * 单价（元）
   */
  "pkgdetail_price": number;
}

