/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 套餐管理
 */
export interface GwPackagesIdData {
  /**
   * 创建人
   */
  "adder"?: number;
  /**
   * 创建时间
   */
  "addtime"?: string;
  /**
   * 0:未知，1：未删除，2：已删除
   */
  "deleteStatus"?: number;
  /**
   * 修改人
   */
  "moder"?: number;
  /**
   * 修改时间
   */
  "modtime"?: string;
  /**
   * 套餐ID
   */
  "packageid"?: number;
  /**
   * 套餐号
   */
  "pkg_code"?: string;
  /**
   * 上架日期
   */
  "pkg_createtime"?: string;
  /**
   * 下架日期
   */
  "pkg_exittime"?: string;
  /**
   * 今日关注人数
   */
  "pkg_follows"?: number;
  /**
   * 套餐说明
   */
  "pkg_info"?: string;
  /**
   * 是否仅限堂食
   */
  "pkg_isinhouse"?: number;
  /**
   * 是否新品
   */
  "pkg_isnew"?: number;
  /**
   * 是否需要预约
   */
  "pkg_isorder"?: number;
  /**
   * 是否强烈推荐
   */
  "pkg_isrecommend"?: number;
  /**
   * 是否支持退款
   */
  "pkg_isrefund"?: number;
  /**
   * 更多优惠链接地址
   */
  "pkg_links"?: string;
  /**
   * 人数
   */
  "pkg_people"?: number;
  /**
   * 套餐标题
   */
  "pkg_title"?: string;
  /**
   * 套餐类别
   */
  "pkg_type"?: string;
  /**
   * 有效期（天）
   */
  "pkg_validdays"?: number;
  /**
   * 生效日期
   */
  "pkg_validtime"?: string;
  /**
   * 店铺号
   */
  "shop_code"?: string;
}

