/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 用户管理
 */
export interface GwUsersIdData {
  /**
   * 创建人
   */
  "adder"?: number;
  /**
   * 创建时间
   */
  "addtime"?: string;
  /**
   * 0:未知，1：未删除，2：已删除
   */
  "deleteStatus"?: number;
  /**
   * 修改人
   */
  "moder"?: number;
  /**
   * 修改时间
   */
  "modtime"?: string;
  /**
   * 用户金币数量
   */
  "user_golds"?: number;
  /**
   * 用户名
   */
  "user_name"?: string;
  /**
   * 手机号
   */
  "user_phone"?: string;
  /**
   * 用户ID
   */
  "userid"?: number;
}

