/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 抵用券管理
 */
export interface GwVouchers1Data {
  /**
   * 是否成功
   */
  "result"?: boolean;
  /**
   * 抵用券ID
   */
  "voucherid"?: number;
}

