/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface SetmealSelectAllSetMealBody {
  /**
   * 用餐最小人数
   */
  "minPepople"?: string;
  /**
   * 用餐最大人数
   */
  "maxPeople"?: string;
  /**
   * 是否需要预约（0：否：1是）
   */
  "isOrder"?: string;
  /**
   * 是否新品（0：否：1是）
   */
  "isNew"?: string;
  /**
   * 套餐类型（暂时写1）
   */
  "setMealType"?: string;
  /**
   * 是否已经被购买（0：否：1是）
   */
  "isBuyed"?: string;
}

