/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface SysDictionarycategorys {
  /**
   * 错误码，成功为\"ok\"
   */
  "code": number;
  /**
   * 字典分类列表
   */
  "data"?: Array<models.SysDictionarycategorysData>;
  /**
   * 错误信息
   */
  "message": string;
}

