/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 字典分类
 */
export interface SysDictionarycategorys1Data {
  /**
   * 字典分类ID
   */
  "dictionarycategoryid"?: number;
  /**
   * 是否成功
   */
  "result"?: boolean;
}

