/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 字典分类
 */
export interface SysDictionarycategorysIdData {
  /**
   * 创建人
   */
  "adder"?: number;
  /**
   * 创建时间
   */
  "addtime"?: string;
  /**
   * 字典类别key
   */
  "categorykey"?: string;
  /**
   * 字典类别value
   */
  "categoryvalue"?: string;
  /**
   * 0:未知，1：未删除，2：已删除
   */
  "deleteStatus"?: number;
  /**
   * 字典分类ID
   */
  "dictionarycategoryid"?: number;
  /**
   * 修改人
   */
  "moder"?: number;
  /**
   * 修改时间
   */
  "modtime"?: string;
}

